server:
  port: 8080

spring:
  application:
    name: notification-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@localhost:27017/notification_db?authSource=admin}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.add.type.headers: true
        spring.json.trusted.packages: "com.transferencia_service.event"

  mail:
    host: ${MAIL_HOST:mailhog}
    port: ${MAIL_PORT:1025}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    protocol: smtp
    properties:
      mail:
        debug: true
        smtp:
          auth: false
          starttls:
            enable: false
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

app:
  frontend:
    url: ${FRONTEND_URL:http://localhost:3000}

kafka:
  topics:
    user-created: ${KAFKA_TOPIC_USER_CREATED:user-created-topic}
    transaction-notification: ${KAFKA_TOPIC_TRANSACTION_NOTIFICATION:transaction-notification-topic}
    password-reset: ${KAFKA_TOPIC_PASSWORD_RESET:password-reset-topic}

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    org.springframework.web: DEBUG
    org.springframework.mail: DEBUG
    org.eclipse.angus.mail: DEBUG
    jakarta.mail: DEBUG
    com.transferencia_service: DEBUG