server:
  port: 8083

spring:
  data:
    mongodb:
      uri: mongodb://mongo_notifications:27017/notifications_db

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: admin
    password: admin
