server:
  port: 8080

spring:
  application:
    name: bank-account-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://admin:admin123@localhost:27017/bank_account_db?authSource=admin}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    consumer:
      group-id: bank-account-service-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

kafka:
  topics:
    # Consome
    user-created: ${KAFKA_TOPIC_USER_CREATED:user-created-topic}
    transfer-validated: ${KAFKA_TOPIC_TRANSFER_VALIDATED:transfer-validated-topic}

    #Produz
    bank-account-created: ${KAFKA_TOPIC_BANK_ACCOUNT_CREATED:bank-account-created-topic}
    transfer-completed: ${KAFKA_TOPIC_TRANSFER_COMPLETED:transfer-completed-topic}

logging:
  level:
    root: INFO
    org.springframework.kafka: DEBUG
    com.bank_account: DEBUG