server:
  port: 8081

spring:
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION:86400000}

logging:
  level:
    root: INFO
    com.user: DEBUG